MQTT:
    MQTT_ip: 192.168.XXX.XXX
    MQTT_USER: 'MQTTUSER'
    MQTT_PW: 'MQTTPASSWORD'
MESHTASTIC:
    CHANNEL_ID: 'ShortFast' # the name of your channel
    CLIENT_ID: '12345678' #the id for your program to use
    GATEWAY_ID: '!12345678' # Your gateway's id
    COMMON_PORTS: 
                  - ["1", "TEXT_MESSAGE_APP"]
                  - ["2", "REMOTE_HARDWARE_APP"]
                  - ["3", "POSITION_APP"]
                  - ["4", "NODEINFO_APP"]
                  - ["5", "ROUTING_APP"]
                  - ["6", "ADMIN_APP"]
                  - ["7", "TEXT_MESSAGE_COMPRESSED"]
                  - ["8", "WAYPOINT_APP"]
                  - ["32", "REPLY_APP"]
                  - ["65", "STORE_FORWARD_APP"]
                  - ["66", "RANGE_TEST_APP"]
                  - ["67", "TELEMETRY_APP"]
                  - ["68", "ZPS_APP"]
    EXTRA_PORTS:
              - PORT_NUMBER: 260
                PORT_NAME: 'TEMPERATURE'
                HA_CLASS: temperature 
              - PORT_NUMBER: 261
                PORT_NAME: 'HUMIDITY'
                HA_CLASS: humidity